### ISSUE TITLE
[1.18.1] Crash when repairing bronze adze with bronze from easysteel.

### ISSUE THREAD

**Issue by Baggytrousers27** [coolsimulations/MoreThanAPickaxe#1]
Forge 1.18.1 39.0.48
SurvivalPlus-1.18.1-0.1.6
MoreThanAPickaxe-1.18.1-0.1.6
EasySteel-Forge-1.18.1-1.5.10
Cucumber-1.18.1-5.0.2
PickleTweaks-1.18.1-6.0.1

With Pickletweaks' crafting grid repair, putting a bronze adze into a crafting grid with a bronze ingot (Both EasySteel and survivalplus) causes a crash.

[Crashlog](https://pastebin.com/xpZ9gimp)

**Comment by coolsimulations** [comment]
Thanks for finding this! This seems to be an issue on SurvivalPlus' end. Looks like an issue that only applies to Forge versions later than 39.0.18 (the tag update). Anyway, I have fixed it and it'll release with the next 0.1.6b update that will come out in the next 48hrs.

**Comment by Baggytrousers27** [comment]
Cheers and thanking you muchly.
